# NOTE: Auto-generated by workflow in mycli-app repo. Do not edit manually.
cask "mycli-app-venv" do
  version "0.1.2"
  arch arm: "arm64", intel: "x86_64"
  sha256 arm: "1c08b0414ae47c2ddda605ad3b9b7ea269ae4370ee0639f655c188c0c0e9e349", intel: "97547037a212be3715c0e1e8a0050bab352589195b769b0811300836ea699515"

  # Asset naming convention for v0.1.2: mycli-<version>-macos-<arch>.tar.gz
  # Example: mycli-0.1.2-macos-arm64.tar.gz
  url "https://github.com/naga-nandyala/mycli-app/releases/download/v#{version}/mycli-#{version}-macos-#{arch}.tar.gz"

  name "MyCLI App (Venv Bundle)"
  desc "Simple Azure-like CLI (portable virtual environment bundle with Azure + MSAL broker)"
  homepage "https://github.com/naga-nandyala/mycli-app"

  depends_on macos: ">= :catalina"

  binary "mycli-#{arch}/bin/mycli", target: "mycli"

  caveats <<~EOS
    Installs a portable Python virtual environment containing all dependencies.
    Features:
      * Azure authentication (azure-identity, azure-core, msal[broker])
      * Native arm64 & x86_64 wheels
      * Offline capable after install

    Usage:
      mycli --help
      mycli login
      mycli status

    For the PyInstaller variant use:
      brew install naga-nandyala/mycli-app/mycli-app
  EOS

  test do
    assert_match "MyCliApp version", shell_output("mycli --version")
  end
end