# NOTE: Auto-generated by workflow in mycli-app repo. Do not edit manually.
cask "mycli-app-venv" do
  version "1.0.0"

  on_arm do
    sha256 "c0b863fa3e6f983b92e7f293baeb3c5b4342f815456a02a6069795e726fc05fb"
    url "https://github.com/naga-nandyala/mycli-app/releases/download/v#{version}/mycli-arm64-1.0.0-arm64.tar.gz"
    binary "mycli-arm64/bin/mycli", target: "mycli"
  end

  on_intel do
    sha256 "2141f2ba8a35239ddd83bde90f03f62e87105b51943d51a135563510061ec547"
    url "https://github.com/naga-nandyala/mycli-app/releases/download/v#{version}/mycli-x86_64-1.0.0-x86_64.tar.gz"
    binary "mycli-x86_64/bin/mycli", target: "mycli"
  end

  name "MyCLI App (Venv Bundle)"
  desc "Simple Azure-like CLI (portable virtual environment bundle with Azure + MSAL broker)"
  homepage "https://github.com/naga-nandyala/mycli-app"

  depends_on macos: ">= :catalina"

  caveats <<~EOS
    Installs a portable Python virtual environment containing all dependencies.
    Features:
      * Azure authentication (azure-identity, azure-core, msal[broker])
      * Native arm64 & x86_64 wheels
      * Offline capable after install

    Usage:
      mycli --help
      mycli login
      mycli status

    For the PyInstaller variant use:
      brew install naga-nandyala/mycli-app/mycli-app
  EOS
end