# NOTE: Auto-generated by workflow in mycli-app repo. Do not edit manually.
cask "mycli-app-pkg" do
  version "1.0.0"

  sha256 "TBD_PKG_SHA256"
  url "https://github.com/naga-nandyala/mycli-app/releases/download/v#{version}/mycli-app-#{version}.pkg"

  name "MyCLI App (PKG Installer)"
  desc "Simple Azure-like CLI distributed as macOS installer package"
  homepage "https://github.com/naga-nandyala/mycli-app"

  # Use pkg installer instead of extracting archives
  pkg "mycli-app-#{version}.pkg"

  # Specify where the binary will be installed by the .pkg
  binary "/usr/local/bin/mycli"

  depends_on macos: ">= :catalina"

  # Optional: Uninstall script if your .pkg doesn't provide one
  uninstall script: {
    executable: "/usr/local/bin/mycli-uninstall.sh",
    sudo:       true
  }

  # Alternative uninstall method - manual file removal
  # uninstall delete: [
  #   "/usr/local/bin/mycli",
  #   "/usr/local/lib/mycli-app"
  # ]

  caveats <<~EOS
    Installs via macOS installer package (.pkg).
    Features:
      * Native macOS installer experience
      * Proper system integration
      * Azure authentication (azure-identity, azure-core, msal[broker])
      * System-wide installation in /usr/local/bin

    Usage:
      mycli --help
      mycli login
      mycli status

    For other variants use:
      brew install naga-nandyala/mycli-app/mycli-app        # PyInstaller
      brew install naga-nandyala/mycli-app/mycli-app-venv   # Venv bundle
      brew install naga-nandyala/mycli-app/mycli-app-src    # Source build
  EOS

  # Optional: Check that the installation was successful
  postflight do
    system_command "/usr/local/bin/mycli", args: ["--version"]
    
    # Verify Azure dependencies are included
    if File.exist?("/usr/local/bin/mycli-verify-dependencies.sh")
      system_command "/usr/local/bin/mycli-verify-dependencies.sh"
    end
  end
end