# GitHub Actions workflow to build and release macOS binaries for mycli
# Auto-created from macos_homebrew/workflow template.

name: build-release-binaries (Manual)

# Ensure GITHUB_TOKEN can create releases
permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version string (e.g. 1.2.3)'
        required: true
        default: '0.1.0'
      create_release:
        description: 'Create GitHub Release (true/false)'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  build-macos:
    name: macOS ${{ matrix.arch }} build
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: arm64
            runner: macos-14
          - arch: x86_64
            runner: macos-13
    env:
      PYTHON_VERSION: '3.12'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller build
          # Install project (uses pyproject.toml for dependencies). Set MYCLI_EXTRAS (e.g. azure,broker) to include extras.
          if [ "${MYCLI_EXTRAS:-}" != "" ]; then
            pip install ".[${MYCLI_EXTRAS}]"
          else
            pip install .
          fi

      - name: Build binary (spec file)
        run: |
          # Set MYCLI_WITH_AZURE=1 in job/env or before this line to include optional azure packages.
          pyinstaller macos_homebrew/pyinstaller/mycli.spec --clean
          echo "PyInstaller build finished. Contents of dist/:"
          ls -R dist

      - name: Package
        run: |
          INPUT_VERSION='${{ github.event.inputs.version }}'
          CODE_VERSION=$(grep '__version__' src/mycli_app/__init__.py | cut -d '"' -f2)
          if [ "$INPUT_VERSION" != "$CODE_VERSION" ]; then
            echo "Warning: input version ($INPUT_VERSION) != code version ($CODE_VERSION). Using input." >&2
            VERSION="$INPUT_VERSION"
          else
            VERSION="$CODE_VERSION"
          fi
          ARCH=${{ matrix.arch }}
          # Binary path differs when using spec (folder build). Adjust if needed.
          if [ -f dist/mycli ]; then
            cp dist/mycli mycli
          elif [ -f dist/mycli/mycli ]; then
            cp dist/mycli/mycli mycli
          else
            echo "Could not locate built binary" >&2
            exit 1
          fi
          chmod +x mycli
          TAR_NAME="mycli-${VERSION}-macos-${ARCH}.tar.gz"
          tar -czf "$TAR_NAME" mycli
          shasum -a 256 "$TAR_NAME" > "$TAR_NAME.sha256"
          echo "TAR_NAME=$TAR_NAME" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mycli-macos-${{ matrix.arch }}
          path: |
            *.tar.gz
            *.tar.gz.sha256

  release:
    needs: build-macos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Extract version
        id: set_version
        run: |
          # Find first version from tarball names
          V=$(find artifacts -name 'mycli-*-macos-*.tar.gz' | head -n1 | sed -E 's/.*mycli-([0-9]+\.[0-9]+\.[0-9]+)-macos-.*/\1/')
          if [ -z "$V" ]; then echo "Could not determine version" >&2; exit 1; fi
          echo "Detected version: $V"
          echo "version=$V" >> $GITHUB_OUTPUT

      - name: Display artifacts
        run: ls -R artifacts

      - name: Prepare release assets
        run: |
          mkdir upload
          find artifacts -name '*.tar.gz' -exec cp {} upload/ \;
          find artifacts -name '*.sha256' -exec cp {} upload/ \;

      - name: Create Release
        if: ${{ github.event.inputs.create_release == 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          files: upload/*
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ steps.set_version.outputs.version }}
          name: mycli v${{ steps.set_version.outputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
