name: Update Homebrew Formula

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update formula for (e.g., 0.1.0). Leave empty to use latest release.'
        required: false
        type: string

permissions:
  contents: write

jobs:
  update-formula:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        pip install requests
        
    - name: Update Homebrew formula
      run: |
        cd macos_homebrew
        python update_formula.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Formula/mycli.rb
        if [ "${{ github.event_name }}" = "release" ]; then
          COMMIT_MSG="Update Homebrew formula for release ${{ github.event.release.tag_name }}"
        else
          COMMIT_MSG="Update Homebrew formula (manual trigger)"
        fi
        git diff --staged --quiet || git commit -m "$COMMIT_MSG"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
